[target.x86_64-unknown-linux-musl]
rustflags = ["-C", "target-feature=+crt-static", "-Z", "location-detail=none"]

[unstable]
build-std = ["panic_abort", "std"]
build-std-features = ["panic_immediate_abort"]

[build]
target = "x86_64-unknown-linux-musl"